CONTACT_NAME = "Contact Name"
CONTACT_EMAIL = "Contact Email"
COMPANY_NUMBER = "Companies House Registration Number"
COMPANY_WEBSITE = "Company website"

TRIAGE_SALES = "Turnover last year (in GBP £)"
TRIAGE_SKU_NUMBER = "Your current stock-keeping units (SKU) of your products"
TRIAGE_TRADEMARKED = "Are your products trademarked in your target countries?"
TRIAGE_TRANSLATION = ""
TRIAGE_DESCRIPTION = ""
