CONTACT_NAME = "Contact name"
CONTACT_EMAIL = "Contact email"
COMPANY_NUMBER = "Companies House Number"
COMPANY_WEBSITE = "Company website"

TRIAGE_SALES = "Turnover last year (in GBP £)"
TRIAGE_SKU_NUMBER = "Number of stock keeping units (SKU) of your products"
TRIAGE_TRADEMARKED = "Are your products trademarked in your target countries?"
TRIAGE_TRANSLATION = "Translation capabilities"
TRIAGE_DESCRIPTION = "Company description"
